pongo.sh

previously this would fail with an unclear error message

fix(shell) auto-build image with shell action

---

README.md
docker-compose.yml
pongo.sh

Rewrote the dependency management to be more flexible,
parametrized.

feat(redis) add redis as a potential dependency

---

docker-compose.yml
pongo.sh

Added to the shell environment, also moved the license variable
from the yml to the script to be more consistent

fix(pongo) added log-level and anonymous-reports variables

---

pongo.sh

since Gojira uses 'nuke' we added this for consistency
fixes #30

feat(nuke) added a nuke command as an alias to clean

---

assets/Dockerfile
assets/busted_helper.lua
pongo.sh

see also: https://github.com/Olivine-Labs/busted/pull/623

fix(busted) add helper for ffi.typeof caching

---

README.md
assets/Dockerfile
assets/pongo_pack
assets/test_plugin_entrypoint.sh
pongo.sh

See individual commits;
* add LuaJIT to the path
* if running external setup script, make sure to return to proper work dir
* add a 'pack' command to pack rockspecs for distribution

adding a 'pack' command and a fix

---

README.md
assets/set_variables.sh
pongo.sh

set the default per project by adding them to a `.pongorc` file

feat(config) add a '.pongorc' file for 'run' and 'up' commands

---

README.md
pongo.sh

Only applies to Kong Enterprise. Instead of adding the license
secret a Bintray package can be added (`BINTRAY_REPO` variable)
where the license will be downloaded from.

feat(license) auto download license without setting it explicitly

---

pongo.sh

And some colors, ruthlessly stolen from Gojira  \o/

feat(shell) add a prompt indicating Kong version

---

pongo.sh

Official images take a while to become available due to Docker
reviews. Hence for a few days the image maybe listed in Pongo
but unavailable for download. In those cases fallback to the
unofficial Kong repo which will have the image after the release.
fixes #63

fix(pull) use fallback if official image unavailable

---

assets/set_variables.sh
assets/update_versions.sh
pongo.sh

Colorized and prefixed messages to make the Pongo output
stand out between the docker, compose, and build logs

feat(log) provide cleaner Pongo information

---

README.md
assets/docker-compose.yml
assets/set_variables.sh
assets/test_plugin_entrypoint.sh
pongo.sh

FEAT: Custom dependencies

---

.shellcheckrc
.travis.yml
Makefile
assets/add_version.sh
assets/ci/README.md
assets/ci/pongo_build.test.sh
assets/ci/pongo_shell.test.sh
assets/ci/test.sh
assets/set_variables.sh
assets/test_plugin_entrypoint.sh
assets/update_versions.sh
pongo.sh

implements:
- test helpers
- tests for `pongo build`
- tests for `pongo shell`

first ci setup

---

assets/set_variables.sh
pongo.sh

Each line prefixed, and on Travis all lines colorized

fix(output) display multi line messages properly

---

assets/help/init.txt
assets/help/shell.txt
pongo.sh

History is stored per plugin. 'pongo init' will add the history
file to the '.gitignore' file

feat(shell) retain the shell history

---

README.md
pongo.sh

This script runs on the host before the container starts

feat(setup) add a pre-run script

---

.travis.yml
README.md
assets/Dockerfile
assets/ci/pongo_luacov.test.sh
assets/help/init.txt
assets/init/luacov
assets/test_plugin_entrypoint.sh
pongo.sh

support is limited to unit tests, since LuaCov doesn't play nice with Openresty

feat(luacov) added support for LuaCov code coverage (limited)

---

pongo.sh

looks like 'docker-compose' is going to be deprecated
alternative to #198

fix(compose) update to new 'docker compose' command

---

README.md
assets/help/docs.txt
assets/help/pongo.txt
pongo.sh

it will render the Kong helper documentation and open it.

feat(docs) add a new docs command

---

.travis.yml

bumping the build worker version includes the necessary docker upgrade
related:
https://github.com/Kong/kong-pongo/pull/204
https://github.com/Kong/docker-kong/pull/495

chore(ci): upgrade build worker and docker version

---

.gitignore
README.md
assets/update_versions.sh

cleanup repo clones and add readme warning

---

pongo.sh

When starting the environment Pongo wouldn't login, causing the
postgres/cassandra/redis pull to hit rate-limits.

fix(login) docker login upon 'pongo up'

---

README.md
assets/Dockerfile
pongo.sh

also makes it easier to debug the build of the docker image

fix(httpie) python3-dev package required to build httpie 

---

README.md
assets/Dockerfile
assets/kong_migrations_start.sh
assets/kong_start_dbless.sh
assets/parse_git_branch.sh
assets/pongo_profile.sh

refactor(shell) move complex aliases into scripts

---

.gitignore
README.md
assets/Dockerfile
assets/kong_export.sh
assets/kong_migrations_start.sh
assets/kong_start_dbless.sh
assets/pongo_profile.sh

also updates other aliases to first try the kong default file;
kong.yml, and adds an explanation when shelling into container

feat(shell) add kx alias to export config

---

.gitignore
assets/kong_export.sh

now deleting the file before the export

fix(shell) kx would not overwrite existing file

---

README.md
assets/kong_migrations_start.sh

workaround for https://github.com/Kong/kong/issues/9365

fix(shell) workaround for import after dbless

---

README.md

to make for a better landing next time, whilst keeping dogfooding Pongo.

chore(docs) update release instructions

---

README.md

Please be aware there is also a new package 'wsl' made available by microsoft corportation. If that is preferred over 'Debian' we need to correct the wording to search by 'wsl' and install 'WSL', vice-versa.

Corrected misleading search term

---

README.md
assets/docker-compose.yml
assets/help/up.txt
pongo.sh

support to globally disable health checks

---

CHANGELOG.md
README.md
pongo.sh

for release status see: https://github.com/Kong/kong-ee/pull/8204

release 2.10.0

---

assets/help/shell.txt

fix(docs): minor update shell command

---

CHANGELOG.md
README.md
pongo.sh

for release status see: https://github.com/Kong/kong-ee/pull/9302

release 2.11.0

---

CHANGELOG.md
pongo.sh

feat(docker-compose): add FIPS environment variable to docker-compose for busted tests

---

CHANGELOG.md
README.md
pongo.sh

For status see: https://github.com/Kong/kong-ee/pull/10128

release 2.13.0

---

CHANGELOG.md
LICENSE
README.md
pongo.sh

For status see: https://github.com/Kong/kong-ee/pull/11257

release 2.16.0

---

.github/workflows/docker.yml
.github/workflows/lint.yml
.github/workflows/test.yml

Reverts https://github.com/Kong/kong-pongo/pull/680, which seems to have made master red.

Revert "added harden runner to all workflows"
